
---
title: "Chapter 4: Geolocation data"
author: "Dan Nguyen"
date: "August 17, 2015"
output:
  md_document:
    variant: markdown_github
---

## Setup

```{r, message = FALSE}
# Load libraries
library(ggplot2)
require(grid)
library(dplyr)
library(lubridate)
library(rgdal)
library(gdata)

# load my themes:
source("./myslimthemes.R")
theme_set(theme_dan())

# create a data directory
dir.create('./data')

```

Download the map data as before:

```{r, message = F}
fname <- "./data/cb_2014_us_state_20m.zip"
if (!file.exists(fname)){
  url <- "http://www2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_us_state_20m.zip"
  print(paste("Downloading: ", url))
  download.file(url, fname)
}
unzip(fname, exdir = "./data/shp")

# Read the map data
us_map <- readOGR("./data/shp/cb_2014_us_state_20m.shp", "cb_2014_us_state_20m")
states_map <- us_map[!us_map$STUSPS %in%
                        c('AS', 'DC', 'GU', 'MP', 'PR', 'VI'),]

# For mapping purposes, we'll make a contiguous-states only
cg_map <- states_map[!states_map$STUSPS %in% c('AK', 'HI'), ]
# And for Oklahoma
ok_map <- states_map[states_map$STUSPS == 'OK', ]

```


Download the quakes data as before:


```{r, message = F}
fn <- './data/usgs-quakes-dump.csv'
zname <- paste(fn, 'zip', sep = '.')
if (!file.exists(zname) || file.size(zname) < 2048){
  url <- paste("https://github.com/dannguyen/ok-earthquakes-RNotebook",
    "raw/master/data", zname, sep = '/')
  print(paste("Downloading: ", url))
  # note: if you have problems downloading from https, you might need to include
  # RCurl
  download.file(url, zname, method = "libcurl")
}
unzip(zname, exdir="data")
# read the data into a dataframe
usgs_data <- read.csv(fn, stringsAsFactors = FALSE)

# Remove all non earthquakes and events with magnitude less than 3.0:
quakes <- usgs_data %>% filter(mag >= 3.0) %>%
  filter(type == 'earthquake')

quakes$year <- year(quakes$time)
quakes$year_month <- strftime(quakes$time, "%Y-%m")
quakes <- mutate(quakes, era = ifelse(year <= 2000, "1995-2000",
          ifelse(year <= 2005, "2001-2005",
          ifelse(year <= 2010, "2006-2010", "2011-2015"))))

# Create a spatial data frame----------------------------------
sp_quakes <- SpatialPointsDataFrame(data = quakes,
                          coords = quakes[,c("longitude", "latitude")])
sp_quakes@proj4string <- states_map@proj4string

# subset for earthquakes in the U.S.
xdf <- over(sp_quakes, states_map[, 'STUSPS'])
states_quakes <- cbind(sp_quakes, xdf) %>% filter(!is.na(STUSPS))

# And for convenience, OK-only
ok_quakes <- filter(states_quakes, STUSPS == 'OK')
```







## Maps


Justify the use of Hexbin map




-------
# get wells




```{r, message = F}
# http://www.occeweb.com/og/ogdatafiles2.htm
fname <- "./data/all_uic_wells.xls"
if (!file.exists(fname)){
  url <- "http://www.occeweb.com/og/all_uic_wells.xls"
  print(paste("Downloading: ", url))
  download.file(url, fname)
}
```

```{r, message = F}
oic_wells <- read.xls(fname)
# this will take a long time
# fixing typos
names(oic_wells)[names(oic_wells)=="LATTITUDE"] <- "LATITUDE"
```

Examine it

```{r}
group_by(oic_wells, STATUS) %>% summarise(count = n()) %>%
    arrange(desc(count))
```




## Injection volumes

```{r, message = F}
# http://www.occeweb.com/og/ogdatafiles2.htm
fname <- "./data/2013_UIC_Injection_Volumes_Report.xls"
if (!file.exists(fname)){
  url <- "http://www.occeweb.com/og/2013%20UIC%20Injection%20Volumes%20Report.xlsx"
  print(paste("Downloading: ", url))
  download.file(url, fname)
}
```


```{r}
oic_injects <- read.xls(fname)
```






-------------
Map it:

```{r}
ggplot() +
  geom_polygon(data = ok_map, aes(x = long, y = lat, group = group),
               fill = "white", color = "black") +
  geom_point(data = filter(oic_wells, STATUS == 'AC', MAXPRESSURE > 000), aes(x = LONGITUDE, y = LATITUDE),
             alpha = 0.1, size = 0.2) +
  geom_point(data = ok_quakes, aes(x = longitude, y = latitude),
             alpha = 0.1, size = 0.2, shape = 1, color = 'red') +
  coord_map("albers", lat0 = 38, latl = 42) + theme_dan_map()
```





<!--
To render this file:
library(rmarkdown)
setwd("~/Dropbox/rprojs/ok-earthquakes-Rnotebook/")

this_file <- 'chapter-4-geocorrelation.Rmd'
render(this_file, output_dir = './builds',
  html_document(toc = TRUE, self_contained = F))

render(this_file, output_dir = './builds',
  md_document(variant = "markdown_github",
              preserve_yaml = TRUE))
-->



