
# Chapter 1: Background on Oklahoma's Earthquakes


http://www.newyorker.com/magazine/2015/04/13/weather-underground

[NPR's StateImpact project has been covering the issue for the past few years](https://stateimpact.npr.org/oklahoma/tag/earthquakes/)


For a 3-minute video primer on the issue, check out this clip by Reveal/The Center for Investigative Reporting:

<iframe width="853" height="480" src="https://www.youtube.com/embed/AIu3b0WhMgs?rel=0" frameborder="0" allowfullscreen></iframe>


### The cause

In a [2013 article from Mother Jones](http://www.motherjones.com/environment/2013/03/does-fracking-cause-earthquakes-wastewater-dewatering):

> Jean Antonides, vice president of exploration for New Dominion, which operates one of the wells near the Wilzetta Fault. He informed me that people claiming to know the true source of the Oklahoma quakes are "either lying to your face or they're idiots."

The industry's general response is that, yes, earthquakes are happening. But that doesn't mean it's _their_ fault. Until recently, they had the backing of the [Oklahoma Geological Survey](http://www.ogs.ou.edu/homepage.php) (OGS). In a [position statement released in February 2014](http://www.ogs.ou.edu/pdf/OGS_POSITION_STATEMENT_2_18_14.pdf):

> Overall, the majority, but not all, of the recent earthquakes appear
to be the result of natural stresses, since they are consistent with the regional Oklahoma natural stress field.


### Current drilling activity



<span id="chapter-1-mark"></span>



## The U.S. Geological Survey Earthquake Data


For quick access, the USGS provides real-time data feeds for time periods between an hour to the last 30 days. The [Feeds & Notifications page](http://earthquake.usgs.gov/earthquakes/feed/v1.0/) shows a menu of data formats and services. For our purposes, the [Spreadsheet Format option](http://earthquake.usgs.gov/earthquakes/feed/v1.0/csv.php) is good enough.


To access the entirety of the USGS data, visit their [Archive page](http://earthquake.usgs.gov/earthquakes/search/).

In Chapter 3, I briefly explain the [relatively simple code for automating the collection of this data](#batch-downloading-historical-data). The process isn't that interesting though so if you just want the zipped up data, you can find it in the [repo's __/data__ directory](https://github.com/dannguyen/ok-earthquakes-RNotebook/tree/master/data), in the file named [usgs-quakes-dump.csv.zip](https://github.com/dannguyen/ok-earthquakes-RNotebook/blob/master/data/usgs-quakes-dump.csv.zip). It weighs in at 27.1MB zipped, 105MB uncompressed.


#### Data attributes

- [time](http://earthquake.usgs.gov/earthquakes/feed/v1.0/glossary.php#time)
- [latitude and longitude](http://earthquake.usgs.gov/earthquakes/feed/v1.0/glossary.php#latitude)
- [mag](http://earthquake.usgs.gov/earthquakes/feed/v1.0/glossary.php#mag), i.e. magnitude
- [type](http://earthquake.usgs.gov/earthquakes/feed/v1.0/glossary.php#type), as in, type of seismic event, which includes earthquakes, explosions, and quarry.
-

## The U.S. Census Cartographic Boundary Shapefiles

https://www.census.gov/geo/maps-data/data/tiger-cart-boundary.html

> The cartographic boundary files are simplified representations of selected geographic areas from the Census Bureau’s MAF/TIGER geographic database.   These boundary files are specifically designed for small scale thematic mapping.

> Generalized boundary files are clipped to a simplified version of the U.S. outline.  As a result, some off-shore areas may be excluded from the generalized files.

> For more details about these files, please see our [Cartographic Boundary File Description page](https://www.census.gov/geo/maps-data/data/cbf/cbf_description.html).

There are shapefiles for various levels of political boundaries. We'll use the ones found on [the states page](https://www.census.gov/geo/maps-data/data/cbf/cbf_state.html). The lowest resolution file -- 1:20,000,000, i.e. 1 inch represents 20 million real inches -- is adequate for our charting purposes.

The direct link to the Census's 2014 1:20,000,000 shape file is [here](https://www.census.gov/geo/maps-data/data/cbf/cbf_counties.html). I've also included it in this repo's `data/` directory.



### Why state boundaries?

The Census shapefiles are conveniently packaged for the analysis we want to do, though we'll find out in Chapter 2 that there's a good amount of complexity in preparing geospatial boundary data for visualization.

But the bigger question is: Are state boundaries really the best way to categorize earthquakes? These boundaries are _political_ and have no correlation with the __seismic__ lines that earthquakes occur along. So, even if we assume _something_ man-made is causing the earthquakes, it could very well be drilling in Texas, or any of Oklahoma's other neighbors, that are causing Oklahoma's earthquake swarm. And conversely, earthquakes caused by Oklahoma drilling but occur within other states' borders will be uncounted when doing a strict state-by-state analysis.

To quote from the [New Yorker](http://www.newyorker.com/magazine/2015/04/13/weather-underground):

> When I spoke to Holland, I had the impression of a man who loved science and was politely trying to endure waking up each day, after insufficient sleep, to discover himself in the role of a politician. At the conference, someone asked Holland about several earthquakes of greater than 4.0 magnitude which had occurred a few days earlier, across Oklahoma’s northern border, in Kansas. Holland joked, “Well, the earthquakes aren’t stopping at the state line, but my problems do.” There was a follow-up question: Why had there previously been no quakes in Kansas—and now for a year and a half there have been so many?






## About the Oklahoma Corporation Commission

http://www.occeweb.com/og/ogdatafiles2.htm
