
```{r, message = FALSE}
library(dplyr)
library(lubridate)
library(rgdal)
library(ggplot2)
library(grid)
require(gridExtra)

```

```{r}
setwd('/tmp')
```


```{r}
bar_theme <-  function(){theme_gray() + theme(
  axis.ticks = element_blank(),
  axis.title = element_blank(),
  axis.text = element_text(color = 'black'),
  axis.text.x = element_blank(),
  panel.background = element_rect(fill = "#EEEEEE"),
  panel.grid.major = element_line(size = 0.2, colour = "white", linetype = "solid"),
  plot.margin = unit(c(0, 0, 0, 0), "cm")
)}
```



Load the earthquakes

```{r, message = FALSE}
url <- "http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_month.csv"
fname <- "all_month.csv"
if (!file.exists(fname)) download.file(url, fname)
usgs_data <- read.csv(fname, stringsAsFactors=FALSE)
```


Histogram

```{r}
g1 <- ggplot(quakes, aes(day(time))) + geom_histogram(binwidth = 1)
```

Line

```{r}
qc <- quakes %>%
  mutate(day = day(time)) %>%
  group_by(day) %>% summarise(counts = n())
g2 <- ggplot(qc, aes(day, counts )) + geom_line()
```

Grid

```{r}
grid.arrange(g1, g2)
```

```{r}
grid.arrange(g1, g1 + bar_theme())
```


Mapping


```{r}
theme_map <- function(base_size = 9, base_family = "") {
  theme_bw(base_size = base_size, base_family = base_family) %+replace% theme(axis.line = element_blank(), axis.text = element_blank(),
    axis.ticks = element_blank(), axis.title = element_blank(), panel.background = element_blank(), panel.border = element_blank(),
    panel.grid = element_blank(), panel.margin = unit(0, "lines"), plot.background = element_blank(), legend.justification = c(0,
      0), legend.position = c(0, 0))
}
```


```{r}
url <- "http://www2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_us_state_5m.zip"
fname <- "cb_2014_us_state_5m.zip"
if (!file.exists(fname)) download.file(url, fname)
unzip(fname, exdir = "shp")
us <- readOGR("shp/cb_2014_us_state_5m.shp", "cb_2014_us_state_5m")

```

Projections

```{r}

uss <- subset(us, !(us$STUSPS %in% c('AK', 'HI', 'AS', 'GU', 'MP', 'PR', 'VI')))

sp_quakes <- SpatialPointsDataFrame(data = quakes,
                                         coords = quakes[,c("longitude", "latitude")])
proj4string(sp_quakes) <- proj4string(uss)

sp_uss_quakes <- sp_quakes[uss,]
uss_quakes <- as.data.frame(sp_uss_quakes)

```




```{r}
ggplot() +
  geom_polygon(data = uss, aes(x = long, y = lat, group = group)) +
  geom_point(data = uss_quakes, aes(x = longitude, y = latitude),
              color = "red", alpha = 0.2, shape = 21) +
  coord_map("albers", lat0 = 39, latl = -42)
```



## Final themes


Bar charts:

```{r}


```


Maps:

```{r}

```
